try(require(dplyr) || install.packages("dplyr"))
try(require(shiny) || install.packages("shiny"))
try(require(ggplot2) || install.packages("ggplot2"))
try(require(stringr) || install.packages("stringr"))
try(require(tidytext) || install.packages("tidytext"))
try(require(wordcloud) || install.packages("wordcloud"))

library(dplyr)
library(shiny)
library(ggplot2)
library(stringr)
library(tidytext)
library(wordcloud)